# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'MyAir' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'ObjectMapper', '~> 3.1'
  pod 'Charts', :inhibit_warnings => true
  pod 'YNDropDownMenu'
  #pod 'GoogleMaps'
  # Pods for MyAir

end
